/**
 * Type generation command
 *
 * Generates TypeScript interfaces and Zod schemas from CMS schemas
 */

import chalk from 'chalk'
import ora from 'ora'
import { loadConfig } from '../config/loader.js'
import { TypeGenerator } from '../typegen/TypeGenerator.js'
import { writeFileSync, mkdirSync } from 'fs'
import { dirname } from 'path'

interface TypegenOptions {
  adapter?: string
  output?: string
  config?: string
  zod?: boolean
  watch?: boolean
}

export async function typegenCommand(options: TypegenOptions): Promise<void> {
  const spinner = ora('Loading configuration...').start()

  try {
    // Load configuration
    const config = await loadConfig(options.config)

    // Validate adapter option
    const adapterOption = options.adapter || config.adapter
    const adapterName = typeof adapterOption === 'string' ? adapterOption : adapterOption?.name
    if (!adapterName) {
      spinner.fail('No adapter specified')
      console.log('')
      console.log(chalk.yellow('Please specify an adapter:'))
      console.log('')
      console.log(`  ${chalk.cyan('--adapter sanity')}      Generate types from Sanity schemas`)
      console.log(`  ${chalk.cyan('--adapter payload')}     Generate types from Payload schemas`)
      console.log(`  ${chalk.cyan('--adapter contentful')}  Generate types from Contentful schemas`)
      console.log(`  ${chalk.cyan('--adapter strapi')}      Generate types from Strapi schemas`)
      console.log('')
      console.log('Or add it to your contentbridge.config.ts:')
      console.log('')
      console.log(chalk.gray('  export default {'))
      console.log(chalk.gray(`    adapter: 'sanity',`))
      console.log(chalk.gray('    // ... other config'))
      console.log(chalk.gray('  }'))
      console.log('')
      process.exit(1)
    }

    spinner.text = `Initializing ${adapterName} adapter...`

    // Create type generator
    const generator = await TypeGenerator.create(adapterName, config)

    spinner.text = 'Fetching schemas...'

    // Get schemas from adapter
    const schemas = await generator.getSchemas()

    if (schemas.length === 0) {
      spinner.warn('No schemas found')
      console.log('')
      console.log(chalk.yellow('Make sure your CMS has schemas defined and your adapter is properly configured.'))
      return
    }

    spinner.text = `Generating types for ${schemas.length} schema(s)...`

    // Generate TypeScript types
    const outputPath = options.output || config.outputPath || 'src/types/contentbridge.generated.ts'
    const generatedTypes = await generator.generateTypes(schemas, {
      format: options.zod ? 'both' : 'typescript',
      includeDocumentation: true,
      strict: true,
      includeHelpers: true,
    })

    // Create output directory if it doesn't exist
    const outputDir = dirname(outputPath)
    mkdirSync(outputDir, { recursive: true })

    // Write types to file
    const fileContent = [
      '/**',
      ' * Generated by ContentBridge CLI',
      ' * Do not edit this file manually',
      ` * Generated from ${adapterName} schemas on ${new Date().toISOString()}`,
      ' */',
      '',
      ...generatedTypes.imports,
      '',
      generatedTypes.interfaces,
    ].join('\n')

    writeFileSync(outputPath, fileContent, 'utf-8')

    // Generate Zod schemas if requested
    if (options.zod && generatedTypes.schemas) {
      const zodPath = outputPath.replace(/\.ts$/, '.zod.ts')
      const zodContent = [
        '/**',
        ' * Generated Zod schemas by ContentBridge CLI',
        ' * Do not edit this file manually',
        ` * Generated from ${adapterName} schemas on ${new Date().toISOString()}`,
        ' */',
        '',
        'import { z } from \'zod\'',
        '',
        generatedTypes.schemas,
      ].join('\n')

      writeFileSync(zodPath, zodContent, 'utf-8')

      spinner.succeed(`Generated types and Zod schemas`)
      console.log('')
      console.log(`  ${chalk.green('✓')} Types:  ${chalk.cyan(outputPath)}`)
      console.log(`  ${chalk.green('✓')} Schemas: ${chalk.cyan(zodPath)}`)
    } else {
      spinner.succeed('Generated types')
      console.log('')
      console.log(`  ${chalk.green('✓')} ${chalk.cyan(outputPath)}`)
    }

    console.log('')
    console.log(chalk.gray(`Generated types for ${schemas.length} schema(s)`))

    // Watch mode
    if (options.watch) {
      console.log('')
      console.log(chalk.blue('Watching for schema changes...'))
      console.log(chalk.gray('Press Ctrl+C to stop'))

      // TODO: Implement watch mode with schema polling
      // This would require adapter support for schema change detection
    }

  } catch (error) {
    spinner.fail('Type generation failed')
    console.log('')

    if (error instanceof Error) {
      console.error(chalk.red('Error:'), error.message)

      if (error.stack && process.env.DEBUG) {
        console.log('')
        console.log(chalk.gray('Stack trace:'))
        console.log(chalk.gray(error.stack))
      }
    }

    process.exit(1)
  }
}
